site_name: Strategic Knowledge Center for undermining crime (docs)  
include_sidebar: false
site_description: 'Documentation from Strategic Knowledge Center for undermining crime'
site_author: 'Team 2 '
docs_dir: docs
repo_name: 'Documentation'
repo_url: 'https://github.com/Team02SE/Documentation'
markdown_extensions:
  - attr_list
  - md_in_html


copyright: <h3><i>Â© 2024 Joint Research Center Zeeland. All Rights Reserved.

theme:
  name: material
  palette:
  - scheme: slate
    primary: red
    accent: red
    toggle: 
      icon: material/weather-sunny 
      name: Switch to dark mode
  - scheme: indigo
    primary: indigo
    accent: indigo
    toggle: 
      icon: material/weather-night
      name: Switch to light mode
 